name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.CONTAINER_REGISTRY }}/tdcpoaaks:$GITHUB_SHA
        docker push ${{ secrets.CONTAINER_REGISTRY }}/tdcpoaaks:$GITHUB_SHA
    - uses: azure/aks-set-context@v1
      with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            cluster-name: tdcpoaaks
            resource-group: tdc-poa
    - name: Create namespace
      run:  |
          if [ -n "$(kubectl get namespace tdc-poa --ignore-not-found -o name)" ]; then exit 0; fi
          kubectl create namespace tdc-poa 
    - uses: azure/k8s-bake@v1
      with:
            renderEngine: 'helm2'
            helmChart: './chart'
            releaseName: todo-microservices
            overrides: |
              image.repository:${{ secrets.CONTAINER_REGISTRY }}/tdcpoaaks
              image.tag:${{ github.sha }}
      id: bake
    - uses: azure/k8s-deploy@v1
      with:
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          namespace: tdc-poa

